#!/bin/bash

# Generates .env.local and .env.cloud for Sorbus deployment.
# Secrets (API_KEY, JWT_SECRET, REFRESH_TOKEN_SECRET) are generated automatically.
# Run this once before starting the containers.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo "=== Sorbus Setup ==="
echo "Generates your .env.local (Pi) and .env.cloud (cloud server) config files."
echo ""

# Verify openssl is available for secret generation
if ! command -v openssl &> /dev/null; then
    echo -e "${RED}Error: openssl is required but not installed.${NC}"
    exit 1
fi

# Prompts for a required value — loops until something is entered
prompt_required() {
    local message="$1"
    local value=""
    while [ -z "$value" ]; do
        read -rp "$message: " value
        [ -z "$value" ] && echo "  This field is required."
    done
    echo "$value"
}

# Prompts with a default value shown in brackets
prompt_default() {
    local message="$1"
    local default="$2"
    local value=""
    read -rp "$message [$default]: " value
    echo "${value:-$default}"
}

# Generate all secrets automatically
echo "Generating secure secrets..."
API_KEY=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)
REFRESH_TOKEN_SECRET=$(openssl rand -hex 32)
echo -e "${GREEN}Done.${NC}"
echo ""

# ── Local machine (Pi) ────────────────────────────────────────────────────────
echo "--- Local Machine (Raspberry Pi) ---"

STORAGE_PATH=$(prompt_required "Absolute path to your file storage directory
  (e.g. /home/pi/sorbus-storage)")

REGISTER_KEY=$(prompt_required "Registration key — users need this to create an account
  (choose something only you share with people you want to allow to sign up)")

CPP_PORT=$(prompt_default "C++ server port" "8080")
MAX_FILES=$(prompt_default "Maximum files to index" "100000")

echo ""

# ── Cloud server ──────────────────────────────────────────────────────────────
echo "--- Cloud Server ---"
echo -e "${YELLOW}Note: if your Cloudflare tunnel is not set up yet, enter CHANGE_ME for the tunnel URL and update .env.cloud later.${NC}"
echo ""

CORS_ORIGIN=$(prompt_required "Your web UI URL — what users type in the browser
  (e.g. https://sorbus.yourdomain.com)")

CPP_SERVER_URL=$(prompt_required "Cloudflare tunnel URL pointing to the C++ server on the Pi
  (e.g. https://cpp.yourdomain.com)")

FRONTEND_PORT=$(prompt_default "Frontend port" "80")

echo ""

# ── Write .env.local ──────────────────────────────────────────────────────────
cat > "$SCRIPT_DIR/.env.local" << EOF
# Generated by setup.sh — do not commit this file
API_KEY=$API_KEY
REGISTER_KEY=$REGISTER_KEY
STORAGE_PATH=$STORAGE_PATH
CPP_PORT=$CPP_PORT
MAX_FILES=$MAX_FILES
EOF

# ── Write .env.cloud ──────────────────────────────────────────────────────────
cat > "$SCRIPT_DIR/.env.cloud" << EOF
# Generated by setup.sh — do not commit this file
API_KEY=$API_KEY
CPP_SERVER_URL=$CPP_SERVER_URL
JWT_SECRET=$JWT_SECRET
REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
CORS_ORIGIN=$CORS_ORIGIN
FRONTEND_PORT=$FRONTEND_PORT
EOF

echo -e "${GREEN}✓ .env.local created${NC}"
echo -e "${GREEN}✓ .env.cloud created${NC}"
echo ""
echo "API_KEY, JWT_SECRET, and REFRESH_TOKEN_SECRET were generated automatically and are not shown."
echo "Keep both .env files private — never commit them."
echo ""
echo "Next steps:"
echo "  On your Pi:          docker compose -f docker-compose.local.yml --env-file .env.local up -d"
echo "  On your cloud server: docker compose -f docker-compose.cloud.yml --env-file .env.cloud up -d"
echo ""
