#!/bin/bash

# Generates .env.local and .env.cloud for Sorbus deployment.
# Secrets (API_KEY, JWT_SECRET, REFRESH_TOKEN_SECRET) are generated automatically.
# Run this once before starting the containers.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo "=== Sorbus Setup ==="
echo "Generates your .env.local (Pi) and .env.cloud (cloud server) config files."
echo ""

# Verify openssl is available for secret generation
if ! command -v openssl &> /dev/null; then
    echo -e "${RED}Error: openssl is required but not installed.${NC}"
    exit 1
fi

# Prompts for a required value — loops until something is entered
prompt_required() {
    local message="$1"
    local value=""
    while [ -z "$value" ]; do
        read -rp "$message: " value
        [ -z "$value" ] && echo "  This field is required." >&2
    done
    echo "$value"
}

# Prompts with a default value shown in brackets
prompt_default() {
    local message="$1"
    local default="$2"
    local value=""
    read -rp "$message [$default]: " value
    echo "${value:-$default}"
}

# Generate all secrets automatically
echo "Generating secure secrets..."
API_KEY=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)
REFRESH_TOKEN_SECRET=$(openssl rand -hex 32)
echo -e "${GREEN}Done.${NC}"
echo ""

# ── Local machine (runs the C++ server natively — see the README) ─────────────
echo "--- Local Machine (where your files live) ---"

FILE_LOCATION=$(prompt_required "Starting folder the app opens on (absolute path)
  (e.g. /home/you/Documents or C:/Users/you/Documents)")

REGISTER_KEY=$(prompt_required "Registration key — users need this to create an account
  (choose something only you share with people you want to allow to sign up)")

echo "Root limit — the storage path may only be set inside this folder."
echo "Leave blank for full filesystem access (any folder/drive on this machine)."
read -rp "Root limit [blank = no limit]: " ROOT_LIMIT

MAX_FILES=$(prompt_default "Maximum files to index in one folder tree" "1000000")

echo ""

# ── Cloud server ──────────────────────────────────────────────────────────────
echo "--- Cloud Server ---"
echo -e "${YELLOW}Note: if your Cloudflare tunnel is not set up yet, enter CHANGE_ME for the tunnel URL and update .env.cloud later.${NC}"
echo ""

CORS_ORIGIN=$(prompt_required "Your web UI URL — what users type in the browser
  (e.g. https://sorbus.yourdomain.com)")

C_Server_Route=$(prompt_required "Cloudflare tunnel URL pointing to the C++ server at home
  (e.g. https://cpp.yourdomain.com)")

FRONTEND_PORT=$(prompt_default "Frontend port" "80")

echo ""

# ── Write .env.local ──────────────────────────────────────────────────────────
cat > "$SCRIPT_DIR/.env.local" << EOF
# Generated by setup.sh — do not commit this file
# These are read directly by the natively-run C++ server (see the README for how to load them).
FILEAPP_API_KEY=$API_KEY
FILEAPP_REGISTER_KEY=$REGISTER_KEY
FILEAPP_FILE_LOCATION=$FILE_LOCATION
FILEAPP_ROOT_LIMIT=$ROOT_LIMIT
FILEAPP_MAX_FILES=$MAX_FILES
EOF

# ── Write .env.cloud ──────────────────────────────────────────────────────────
cat > "$SCRIPT_DIR/.env.cloud" << EOF
# Generated by setup.sh — do not commit this file
API_KEY=$API_KEY
C_Server_Route=$C_Server_Route
JWT_SECRET=$JWT_SECRET
REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
CORS_ORIGIN=$CORS_ORIGIN
FRONTEND_PORT=$FRONTEND_PORT
EOF

echo -e "${GREEN}✓ .env.local created${NC}"
echo -e "${GREEN}✓ .env.cloud created${NC}"
echo ""
echo "API_KEY, JWT_SECRET, and REFRESH_TOKEN_SECRET were generated automatically and are not shown."
echo "Keep both .env files private — never commit them."
echo ""
echo "Next steps:"
echo "  Local machine: run the C++ server natively with the vars in .env.local — see the README ('Running the C++ server')."
echo "  Cloud server:  docker compose -f docker-compose.cloud.yml --env-file .env.cloud up -d"
echo ""
